CREATE TABLE users (
    id INT(100) PRIMARY KEY UNIQUE AUTO_INCREMENT,
    nome VARCHAR(30) NOT NULL,
    tel VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    city VARCHAR(30) NOT NULL,
    endereco VARCHAR(30) NOT NULL
);
